import type { Achievement, Checkin, Location, User } from '@/services/api'

export const mockUser: User = {
  id: 1,
  openid: 'demo_openid',
  nickname: '花园探索者',
  avatar: '',
  level: 8,
  exp: 1250,
  total_checkins: 47,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const mockLocations: Location[] = [
  {
    id: 1,
    name: '狮山樱花径',
    description: '沿着狮山的樱花小径，春天时粉色花海最适合打卡。',
    latitude: '30.4692',
    longitude: '114.3578',
    flower_species: '樱花',
    bloom_status: '盛开中',
    historical_bloom_start: '03月10日',
    historical_bloom_end: '03月25日',
    cover_image: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=720&q=80',
    checkin_count: 68,
    status_updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: '绿意百合角',
    description: '白色百合静静绽放于园区一角，适合静享自然。',
    latitude: '30.4703',
    longitude: '114.3634',
    flower_species: '百合',
    bloom_status: '预计7天开放',
    historical_bloom_start: '04月05日',
    historical_bloom_end: '04月20日',
    cover_image: 'https://images.unsplash.com/photo-1496317899792-9d7dbcd928a5?auto=format&fit=crop&w=720&q=80',
    checkin_count: 39,
    status_updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: '阳光向日葵田',
    description: '金黄向日葵在阳光下微笑，活力满满。',
    latitude: '30.4720',
    longitude: '114.3586',
    flower_species: '向日葵',
    bloom_status: '含苞待放',
    historical_bloom_start: '05月01日',
    historical_bloom_end: '05月15日',
    cover_image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=720&q=80',
    checkin_count: 22,
    status_updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: '浓香牡丹园',
    description: '红紫色牡丹盛开时，花香浓郁而典雅。',
    latitude: '30.4680',
    longitude: '114.3601',
    flower_species: '牡丹',
    bloom_status: '盛开中',
    historical_bloom_start: '04月15日',
    historical_bloom_end: '04月28日',
    cover_image: 'https://images.unsplash.com/photo-1495320521277-0f12c5c221c2?auto=format&fit=crop&w=720&q=80',
    checkin_count: 51,
    status_updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: '清香兰花苑',
    description: '兰花幽香在清风中若隐若现，充满东方雅意。',
    latitude: '30.4710',
    longitude: '114.3625',
    flower_species: '兰花',
    bloom_status: '预计5天开放',
    historical_bloom_start: '04月08日',
    historical_bloom_end: '04月25日',
    cover_image: 'https://images.unsplash.com/photo-1464207551237-040338b17096?auto=format&fit=crop&w=720&q=80',
    checkin_count: 17,
    status_updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockCheckins: Checkin[] = [
  {
    id: 101,
    user_id: 1,
    location_id: 1,
    content: '狮山樱花径的花海太美了，春风轻拂，心情格外舒畅。',
    images: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=720&q=80'
    ],
    likes_count: 12,
    dislikes_count: 1,
    comments_count: 3,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: new Date().toISOString(),
    user: mockUser,
  },
  {
    id: 102,
    user_id: 2,
    location_id: 4,
    content: '牡丹园的色彩层次非常丰富，拍照出来的效果很高级。',
    images: [
      'https://images.unsplash.com/photo-1523731407965-2430cd12f5e4?auto=format&fit=crop&w=720&q=80',
      'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=720&q=80'
    ],
    likes_count: 23,
    dislikes_count: 0,
    comments_count: 6,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      id: 2,
      openid: 'user_2',
      nickname: '花间一壶酒',
      avatar: '',
      level: 5,
      exp: 890,
      total_checkins: 18,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 103,
    user_id: 3,
    location_id: 2,
    content: '百合小角落准备开花了，空气中能闻到一丝清香。',
    images: [],
    likes_count: 8,
    dislikes_count: 0,
    comments_count: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      id: 3,
      openid: 'user_3',
      nickname: '绿叶边',
      avatar: '',
      level: 4,
      exp: 610,
      total_checkins: 14,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 104,
    user_id: 4,
    location_id: 3,
    content: '向日葵田逐渐展开了，远看像一片金黄的海洋。',
    images: [
      'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=720&q=80',
      'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=720&q=80',
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=720&q=80'
    ],
    likes_count: 26,
    dislikes_count: 2,
    comments_count: 9,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      id: 4,
      openid: 'user_4',
      nickname: '秋水伊人',
      avatar: '',
      level: 6,
      exp: 1020,
      total_checkins: 24,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 105,
    user_id: 1,
    location_id: 5,
    content: '兰花苑开始显露花苞，颜色柔和，非常适合静心。',
    images: ['https://images.unsplash.com/photo-1597987335282-a5dd4a6c4569?auto=format&fit=crop&w=720&q=80'],
    likes_count: 5,
    dislikes_count: 0,
    comments_count: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
    updated_at: new Date().toISOString(),
    user: mockUser,
  }
]

export const mockAchievements: Achievement[] = [
  { id: 1, name: '初次打卡', description: '完成一次花卉打卡', icon: '一', requirement: 1, reward_exp: 20 },
  { id: 2, name: '花园探索者', description: '完成5次打卡', icon: '二', requirement: 5, reward_exp: 40 },
  { id: 3, name: '内容创作者', description: '发布3条帖子', icon: '三', requirement: 3, reward_exp: 60 },
  { id: 4, name: '打卡达人', description: '完成20次打卡', icon: '四', requirement: 20, reward_exp: 120 },
]
