"""add achievement name and requirement

Revision ID: 719a22a7ef1f
Revises: b2c3d4e5f6a7
Create Date: 2026-05-27 23:02:53.261425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719a22a7ef1f'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('requirement', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_column('requirement')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
