"""Initial migration

Revision ID: ff5bca9f7110
Revises: 
Create Date: 2026-04-13 17:36:24.543028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5bca9f7110'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flowers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('genus', sa.String(length=100), nullable=True),
    sa.Column('bloom_status', sa.Enum('DORMANT', 'BUDDING', 'BLOOMING', 'WITHERING', name='bloomstatus'), nullable=True),
    sa.Column('historical_bloom_start', sa.String(length=20), nullable=True),
    sa.Column('historical_bloom_end', sa.String(length=20), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('achievements_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('achievements_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievements_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flower_places',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flower_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flower_id'], ['flowers.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('titles_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titles_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['titles_id'], ['titles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flower_place_id', sa.Integer(), nullable=False),
    sa.Column('bloom_report', sa.Enum('DORMANT', 'BUDDING', 'BLOOMING', 'WITHERING', name='bloomstatus'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flower_place_id'], ['flower_places.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkins')
    op.drop_table('titles_users')
    op.drop_table('flower_places')
    op.drop_table('achievements_users')
    op.drop_table('users')
    op.drop_table('titles')
    op.drop_table('places')
    op.drop_table('flowers')
    op.drop_table('achievements')
    # ### end Alembic commands ###
