import type { Achievement, Checkin, Location, Title, User } from '@/services/api'

export const mockUser: User = {
  id: 1,
  openid: 'demo_openid',
  nickname: '花园探索者',
  avatar_url: '',
  level: 8,
  exp: 1250,
  total_checkins: 47,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  current_title: { id: 5, name: '满园春色', description: '阅尽狮山九种花，俯仰皆春', requirement: 9 },
}

// 数据来源：localtion.txt（华农狮山校区 12 个真实花卉点位，手机 GPS 采集 = WGS-84）
// 已通过 scripts/convert-to-gcj02.mjs 转为 GCJ-02（微信/腾讯/高德地图坐标系，可直接渲染）
// 花期与状态以 2026-05-26（暮春初夏）为基准时间推断
const NOW = new Date().toISOString()

export const mockLocations: Location[] = [
  {
    id: 1,
    name: '樱花·樱花路',
    description: '春日樱花路，粉樱列植夹道，是校园最经典的打卡花径。',
    latitude: '30.471260',
    longitude: '114.364961',
    flower_species: '樱花',
    bloom_status: '休眠中',
    historical_bloom_start: '03月20日',
    historical_bloom_end: '04月05日',
    cover_image: '/static/flowers/樱花.png',
    checkin_count: 86,
    status_updated_at: NOW,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 2,
    name: '蔷薇·机电中心旁',
    description: '机电工程训练中心外墙的攀援蔷薇，初夏正是花势最盛之时。',
    latitude: '30.467089',
    longitude: '114.363014',
    flower_species: '蔷薇',
    bloom_status: '盛开中',
    historical_bloom_start: '05月01日',
    historical_bloom_end: '06月15日',
    cover_image: '/static/flowers/蔷薇花.png',
    checkin_count: 42,
    status_updated_at: NOW,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 3,
    name: '蔷薇·三运球场南',
    description: '三运篮球场南侧花丛，红粉相间，黄昏来访最佳。',
    latitude: '30.470983',
    longitude: '114.365239',
    flower_species: '蔷薇',
    bloom_status: '盛开中',
    historical_bloom_start: '05月01日',
    historical_bloom_end: '06月15日',
    cover_image: '/static/flowers/蔷薇花.png',
    checkin_count: 28,
    status_updated_at: NOW,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 4,
    name: '夹竹桃·水产学院旁',
    description: '水产学院教学实习基地旁列植夹竹桃，叶秀花繁。',
    latitude: '30.464034',
    longitude: '114.363292',
    flower_species: '夹竹桃',
    bloom_status: '预计 6 天后绽萼',
    historical_bloom_start: '06月01日',
    historical_bloom_end: '10月15日',
    cover_image: '/static/flowers/夹竹桃.png',
    checkin_count: 5,
    status_updated_at: NOW,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 5,
    name: '夹竹桃·水杉林西',
    description: '水杉林西侧约 100 米，夹竹桃与杉影相映成趣。',
    latitude: '30.465137',
    longitude: '114.358285',
    flower_species: '夹竹桃',
    bloom_status: '预计 6 天后绽萼',
    historical_bloom_start: '06月01日',
    historical_bloom_end: '10月15日',
    cover_image: '/static/flowers/夹竹桃.png',
    checkin_count: 3,
    status_updated_at: NOW,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 6,
    name: '油菜花·实验田',
    description: '水杉林周边的油菜花实验田，每到春末已结荚收尾。',
    latitude: '30.466532',
    longitude: '114.361901',
    flower_species: '油菜花',
    bloom_status: '休眠中',
    historical_bloom_start: '03月01日',
    historical_bloom_end: '04月10日',
    cover_image: '/static/flowers/油菜花.png',
    checkin_count: 64,
    status_updated_at: NOW,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 7,
    name: '莲花·水杉林池塘',
    description: '水杉林西侧约 300 米的小池塘，夏初莲叶田田，含苞待放。',
    latitude: '30.466506',
    longitude: '114.346879',
    flower_species: '莲花',
    bloom_status: '预计 20 天后绽萼',
    historical_bloom_start: '06月15日',
    historical_bloom_end: '08月30日',
    cover_image: '/static/flowers/桃花.png',
    checkin_count: 11,
    status_updated_at: NOW,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 8,
    name: '莲花·蕙芷园南池',
    description: '蕙芷园南面池塘，盛夏荷风送香，是校内赏荷首选。',
    latitude: '30.468723',
    longitude: '114.343819',
    flower_species: '莲花',
    bloom_status: '预计 20 天后绽萼',
    historical_bloom_start: '06月15日',
    historical_bloom_end: '08月30日',
    cover_image: '/static/flowers/桃花.png',
    checkin_count: 14,
    status_updated_at: NOW,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 9,
    name: '梨花·三教A座前',
    description: '三教 A 座教学楼前的梨树，早春雪白成阵。',
    latitude: '30.472085',
    longitude: '114.359120',
    flower_species: '梨花',
    bloom_status: '休眠中',
    historical_bloom_start: '03月15日',
    historical_bloom_end: '04月05日',
    cover_image: '/static/flowers/梨花.png',
    checkin_count: 21,
    status_updated_at: NOW,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 10,
    name: '玉兰·图书馆前',
    description: '图书馆门前的白玉兰，每年开学第一周已完成花事。',
    latitude: '30.471248',
    longitude: '114.357451',
    flower_species: '玉兰',
    bloom_status: '惜花·韶华已尽',
    historical_bloom_start: '03月01日',
    historical_bloom_end: '03月25日',
    cover_image: '/static/flowers/玉兰花.png',
    checkin_count: 38,
    status_updated_at: NOW,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 11,
    name: '大金鸡菊·狮子山广场南',
    description: '狮子山广场南面的金鸡菊带，初夏一片明亮金黄。',
    latitude: '30.472916',
    longitude: '114.357730',
    flower_species: '大金鸡菊',
    bloom_status: '盛开中',
    historical_bloom_start: '05月10日',
    historical_bloom_end: '09月20日',
    cover_image: '/static/flowers/大金鸡菊.png',
    checkin_count: 19,
    status_updated_at: NOW,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 12,
    name: '格桑花·蕙芷园北',
    description: '蕙芷园北面的格桑花海，盛花期一直延续到深秋。',
    latitude: '30.471226',
    longitude: '114.344932',
    flower_species: '格桑花',
    bloom_status: '盛开中',
    historical_bloom_start: '05月15日',
    historical_bloom_end: '10月30日',
    cover_image: '/static/flowers/格桑花.png',
    checkin_count: 25,
    status_updated_at: NOW,
    created_at: NOW,
    updated_at: NOW,
  },
]

export const mockCheckins: Checkin[] = [
  {
    id: 101,
    user_id: 1,
    location_id: 2, // 蔷薇·机电中心旁
    content: '机电中心墙头的蔷薇正盛，红粉成片，是这季节最好的打卡机会。',
    images: ['/static/flowers/蔷薇花.png'],
    likes_count: 12,
    comments_count: 3,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: NOW,
    user: mockUser,
  },
  {
    id: 102,
    user_id: 2,
    location_id: 11, // 大金鸡菊·狮子山广场南
    content: '狮子山广场南面的金鸡菊带太亮眼了，金黄一片连绵到翠竹路边。',
    images: ['/static/flowers/大金鸡菊.png', '/static/flowers/格桑花.png'],
    likes_count: 23,
    comments_count: 6,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    updated_at: NOW,
    user: {
      id: 2,
      openid: 'user_2',
      nickname: '花间一壶酒',
      avatar_url: '',
      level: 5,
      exp: 890,
      total_checkins: 18,
      created_at: NOW,
      updated_at: NOW,
      current_title: { id: 4, name: '半园识翠', description: '园中近半花种已识，目力渐熟', requirement: 6 },
    },
  },
  {
    id: 103,
    user_id: 3,
    location_id: 12, // 格桑花·蕙芷园北
    content: '蕙芷园北侧的格桑花开始密密铺开，空气里都是清新的草甸气息。',
    images: [],
    likes_count: 8,
    comments_count: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    updated_at: NOW,
    user: {
      id: 3,
      openid: 'user_3',
      nickname: '绿叶边',
      avatar_url: '',
      level: 4,
      exp: 610,
      total_checkins: 14,
      created_at: NOW,
      updated_at: NOW,
      current_title: { id: 3, name: '三两芳信', description: '收集到三种以上花讯，渐入佳境', requirement: 3 },
    },
  },
  {
    id: 104,
    user_id: 4,
    location_id: 3, // 蔷薇·三运球场南
    content: '三运球场南侧的蔷薇墙最近开得连成一片，黄昏时光线最柔。',
    images: [
      '/static/flowers/蔷薇花.png',
      '/static/flowers/樱花.png',
      '/static/flowers/玉兰花.png',
    ],
    likes_count: 26,
    comments_count: 9,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: NOW,
    user: {
      id: 4,
      openid: 'user_4',
      nickname: '秋水伊人',
      avatar_url: '',
      level: 6,
      exp: 1020,
      total_checkins: 24,
      created_at: NOW,
      updated_at: NOW,
      current_title: { id: 4, name: '半园识翠', description: '园中近半花种已识，目力渐熟', requirement: 6 },
    },
  },
  {
    id: 105,
    user_id: 1,
    location_id: 8, // 莲花·蕙芷园南池
    content: '蕙芷园南面池塘的荷叶已经完全展开，再过些日子就能看到花苞了。',
    images: ['/static/flowers/桃花.png'],
    likes_count: 5,
    comments_count: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
    updated_at: NOW,
    user: mockUser,
  },
]

export const mockAchievements: Achievement[] = [
  { id: 1, name: '初次打卡', description: '完成一次花卉打卡', icon: '一', requirement: 1, reward_exp: 20 },
  { id: 2, name: '花园探索者', description: '完成5次打卡', icon: '二', requirement: 5, reward_exp: 40 },
  { id: 3, name: '内容创作者', description: '发布3条帖子', icon: '三', requirement: 3, reward_exp: 60 },
  { id: 4, name: '打卡达人', description: '完成20次打卡', icon: '四', requirement: 20, reward_exp: 120 },
]

// 与后端 backend/seed_demo_data.py 的 SEED_TITLES 保持一致
export const mockTitles: Title[] = [
  { id: 1, name: '初问春色', description: '初次踏入花径，还未识得校园群芳',     requirement: 0 },
  { id: 2, name: '一径花踪', description: '已识一种花卉，开始留心枝头的春信',   requirement: 1 },
  { id: 3, name: '三两芳信', description: '收集到三种以上花讯，渐入佳境',       requirement: 3 },
  { id: 4, name: '半园识翠', description: '园中近半花种已识，目力渐熟',         requirement: 6 },
  { id: 5, name: '满园春色', description: '阅尽狮山九种花，俯仰皆春',           requirement: 9 },
]
